name: Push trigger for inji-openID4VP

on:
  push:
    branches:
    - master
    - develop
    - qa-develop
    - 'release-**'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
    - master
    - develop
    - qa-develop
    - 'release-**'

jobs:
  build-kotlin:
    uses: mosip/kattu/.github/workflows/gradle-build.yml@master
    with:
      SERVICE_LOCATION: kotlin
      JAVA_VERSION: 17
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_INJI_TEAM }}


